In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


1.Scalar & Array Operations (Redo Section with Your Own Values): Run the given code with scalar = 3.7 and a new array of at least 6 elements.
Show outputs of all built-in mathematical functions (sin, cos, tan, etc.).

In [2]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([11, 32, 7, 2, 9,8])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [-0.99999021  0.55142668  0.6569866   0.90929743  0.41211849  0.98935825]
cos: [ 0.0044257   0.83422336  0.75390225 -0.41614684 -0.91113026 -0.14550003]
tan: [-225.95084645    0.66100604    0.87144798   -2.18503986   -0.45231566
   -6.79971146]
asin: [0.35090734 1.57079633 0.22053326 0.06254076 0.28509644 0.25268026]
acos: [1.21988898 0.         1.35026307 1.50825556 1.28569989 1.31811607]
atan: [1.48013644 1.53955649 1.42889927 1.10714872 1.46013911 1.44644133]
exp: [5.98741417e+04 7.89629602e+13 1.09663316e+03 7.38905610e+00
 8.10308393e+03 2.98095799e+03]
log: [2.39789527 3.4657359  1.94591015 0.69314718 2.19722458 2.07944154]
abs: [11 32  7  2  9  8]
sqrt: [3.31662479 5.65685425 2.64575131 1.41421356 3.         2.82842712]
rem: [1 0 1 0 1 0]
round: [11 32  7  2  9  8]
floor: [11. 32.  7.  2.  9.  8.]
ceil: [11. 32.  7.  2.  9.  8.]


2. 2×2 Matrix Calculations (Already Done in Class):
Study and understand the example code given for trigonometric, exponential, logarithmic, and rounding operations on a 2×2 matrix.

In [3]:
# Creating a 2x2 matrix
matrix = np.array([[-5, 21], [9, -4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[-5 21]
 [ 9 -4]]

sin:
 [[0.95892427 0.83665564]
 [0.41211849 0.7568025 ]]

cos:
 [[ 0.28366219 -0.54772926]
 [-0.91113026 -0.65364362]]

tan:
 [[ 3.38051501 -1.52749853]
 [-0.45231566 -1.15782128]]

asine:
 [[-0.24040422  1.57079633]
 [ 0.44291104 -0.19164719]]

acosine:
 [[1.81120054 0.        ]
 [1.12788528 1.76244352]]

atangent:
 [[-1.37340077  1.52321322]
 [ 1.46013911 -1.32581766]]

exp:
 [[6.73794700e-03 1.31881573e+09]
 [8.10308393e+03 1.83156389e-02]]

log (natural):
 [[       nan 3.04452244]
 [2.19722458        nan]]

abs:
 [[ 5 21]
 [ 9  4]]

sqrt:
 [[       nan 4.58257569]
 [3.                nan]]

rem (remainder when divided by 2):
 [[1 1]
 [1 0]]

round:
 [[-5 21]
 [ 9 -4]]

floor:
 [[-5. 21.]
 [ 9. -4.]]

ceil:
 [[-5. 21.]
 [ 9. -4.]]


/tmp/ipython-input-1325189321.py:14: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
/tmp/ipython-input-1325189321.py:18: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


Task: Apply the Same Operations on a 3×2 Matrix Create a 3×2 matrix with custom values.

Perform and display results of: Trigonometric functions Exponential & logarithmic functions Absolute value & square root Remainder when divided by 2 Rounding (round, floor, ceil)

In [4]:
# Creating a 3x3 matrix
matrix = np.array([[-5, 4], [2, 9],[6,-4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[-5  4]
 [ 2  9]
 [ 6 -4]]

sin:
 [[ 0.95892427 -0.7568025 ]
 [ 0.90929743  0.41211849]
 [-0.2794155   0.7568025 ]]

cos:
 [[ 0.28366219 -0.65364362]
 [-0.41614684 -0.91113026]
 [ 0.96017029 -0.65364362]]

tan:
 [[ 3.38051501  1.15782128]
 [-2.18503986 -0.45231566]
 [-0.29100619 -1.15782128]]

asine:
 [[-0.58903097  0.46055399]
 [ 0.22409309  1.57079633]
 [ 0.72972766 -0.46055399]]

acosine:
 [[2.1598273  1.11024234]
 [1.34670323 0.        ]
 [0.84106867 2.03135032]]

atangent:
 [[-1.37340077  1.32581766]
 [ 1.10714872  1.46013911]
 [ 1.40564765 -1.32581766]]

exp:
 [[6.73794700e-03 5.45981500e+01]
 [7.38905610e+00 8.10308393e+03]
 [4.03428793e+02 1.83156389e-02]]

log (natural):
 [[       nan 1.38629436]
 [0.69314718 2.19722458]
 [1.79175947        nan]]

abs:
 [[5 4]
 [2 9]
 [6 4]]

sqrt:
 [[       nan 2.        ]
 [1.41421356 3.        ]
 [2.44948974        nan]]

rem (remainder when divided by 2):
 [[1 0]
 [0 1]
 [0 0]]

round:
 [[-5  4]
 [ 2  9]
 [ 6 -4]]

floor:
 [[-5. 

/tmp/ipython-input-3953975024.py:14: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
/tmp/ipython-input-3953975024.py:18: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


4.Vector Functions Understand the operations on the 1D vector shown in the notebook.
Task: Perform Same Operations on a 2×3 Matrix Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).

Implement and display:

Max & Min (with indices)

Vector length

Sorted version (both row-wise descending and entire matrix descending)

Sum, Product Median, Mean, Standard Deviation

In [5]:
import numpy as np

# -------------------------------
# 1. Define a 2x3 matrix (floats)
# -------------------------------
mat = np.array([[1.2, 5.5, 3.1],
                [9.4, 2.0, 6.8]])

print("Matrix:\n", mat)

# --------------------------------
# 2. Max / Min values and indices
# --------------------------------
max_value = np.max(mat)
min_value = np.min(mat)

max_index_flat = np.argmax(mat)
min_index_flat = np.argmin(mat)

max_index_2d = np.unravel_index(max_index_flat, mat.shape)
min_index_2d = np.unravel_index(min_index_flat, mat.shape)

print("\nMax value:", max_value, "at index", max_index_2d)
print("Min value:", min_value, "at index", min_index_2d)

# -------------------------------
# 3. Shape, length, and size
# -------------------------------
print("\nLength (rows):", len(mat))
print("Shape:", mat.shape)
print("Total elements:", mat.size)

# -------------------------------
# 4. Sorting
# -------------------------------
# Ascending
sorted_rows = np.sort(mat, axis=1)
sorted_cols = np.sort(mat, axis=0)
sorted_all = np.sort(mat, axis=None)

# Descending
desc_rows = sorted_rows[:, ::-1]
desc_cols = sorted_cols[::-1, :]
desc_all = sorted_all[::-1]

print("\nSorted rows (ascending):\n", sorted_rows)
print("Sorted columns (ascending):\n", sorted_cols)
print("Sorted all elements (ascending):", sorted_all)

print("\nSorted rows (descending):\n", desc_rows)
print("Sorted columns (descending):\n", desc_cols)
print("Sorted all elements (descending):", desc_all)

# -------------------------------
# 5. Sum and Product
# -------------------------------
sum_all = np.sum(mat)
prod_all = np.prod(mat)

sum_rows = np.sum(mat, axis=1)
sum_cols = np.sum(mat, axis=0)

print("\nSum (all):", sum_all)
print("Product (all):", prod_all)
print("Sum per row:", sum_rows)
print("Sum per column:", sum_cols)

# -------------------------------
# 6. Mean, Median, Std Deviation
# -------------------------------
mean_all = np.mean(mat)
median_all = np.median(mat)
std_all = np.std(mat)

mean_rows = np.mean(mat, axis=1)
median_cols = np.median(mat, axis=0)

print("\nMean (all):", mean_all)
print("Median (all):", median_all)
print("Standard deviation (all):", std_all)
print("Mean per row:", mean_rows)
print("Median per column:", median_cols)


Matrix:
 [[1.2 5.5 3.1]
 [9.4 2.  6.8]]

Max value: 9.4 at index (np.int64(1), np.int64(0))
Min value: 1.2 at index (np.int64(0), np.int64(0))

Length (rows): 2
Shape: (2, 3)
Total elements: 6

Sorted rows (ascending):
 [[1.2 3.1 5.5]
 [2.  6.8 9.4]]
Sorted columns (ascending):
 [[1.2 2.  3.1]
 [9.4 5.5 6.8]]
Sorted all elements (ascending): [1.2 2.  3.1 5.5 6.8 9.4]

Sorted rows (descending):
 [[5.5 3.1 1.2]
 [9.4 6.8 2. ]]
Sorted columns (descending):
 [[9.4 5.5 6.8]
 [1.2 2.  3.1]]
Sorted all elements (descending): [9.4 6.8 5.5 3.1 2.  1.2]

Sum (all): 28.000000000000004
Product (all): 2615.6064
Sum per row: [ 9.8 18.2]
Sum per column: [10.6  7.5  9.9]

Mean (all): 4.666666666666667
Median (all): 4.3
Standard deviation (all): 2.864534090485843
Mean per row: [3.26666667 6.06666667]
Median per column: [5.3  3.75 4.95]
